export const AdminTestTableColumns = [
    { name: "Id", uid: "id", sortable: true },
    { name: "Name", uid: "name", sortable: true },
    {name: "Company", uid: "company", sortable: true},
    {name: "Type", uid: "testType", sortable: true},
    {name: "Duration", uid: "duration", sortable: true},
    {name: "PassMark", uid: "passMark", sortable: true},
    {name: "Timed", uid: "isTimed", sortable: true},
    {name: "Shuffle", uid: "shuffleQuestions", sortable: true},
    {name: "MaxAttempt", uid: "maximumAttempts", sortable: true},
    {name: "Question", uid: "questions", sortable: true},
    {name: "Feedback", uid: "feedback", sortable: true},
    {name: "Access", uid: "testAccessControl", sortable: true},
    {name: "Grading", uid: "gradingScheme", sortable: true},
    {name: "RetakePolicy", uid: "retakePolicy", sortable: true},
    {name: "Visibility", uid: "visibility", sortable: true},
    {name: "StartDate", uid: "startDate", sortable: true},
    {name: "EndDate", uid: "endDate", sortable: true},
    { name: "Status", uid: "isActive", sortable: true },
    { name: "Actions", uid: "actions" },
];