const AdminTestTableColumns = [
    { name: "Name", uid: "name", sortable: true },
    { name: "Company", uid: "company", sortable: true },
    { name: "Type", uid: "testType", sortable: true },
    { name: "Duration", uid: "duration", sortable: true },
    { name: "Pass Mark", uid: "passMark", sortable: true },
    { name: "Timed", uid: "isTimed", sortable: true },
    { name: "Shuffle", uid: "shuffleQuestions", sortable: true },
    { name: "Max Attempts", uid: "maximumAttempts", sortable: true },
    { name: "Questions", uid: "questions", sortable: true },
    { name: "Feedback", uid: "feedback", sortable: true },
    { name: "Access", uid: "testAccessControl", sortable: true },
    { name: "Grading", uid: "gradingScheme", sortable: true },
    { name: "Retake Policy", uid: "retakePolicy", sortable: false },
    { name: "Visibility", uid: "visibility", sortable: true },
    { name: "Start Date", uid: "startDate", sortable: true },
    { name: "End Date", uid: "endDate", sortable: true },
    { name: "Status", uid: "isActive", sortable: true },
    { name: "Actions", uid: "actions", sortable: false },
];